---
- name: Getting versions list of current content view
  set_fact:
    current_cv_version_list: "{{ content_view_list.json | json_query(query_ccv_cv_version_list) }}"

- name: Adding latest version id of each content views
  set_fact:
    sat_ccv_component_ids: "{{ sat_ccv_component_ids + [ inner_item.id ] }}"
  when: inner_item.environment_ids is defined and (inner_item.environment_ids|length>0)
  with_list: "{{ current_cv_version_list }}"
  loop_control:
    loop_var: inner_item